version: "3"
services:
  app:
    container_name: zappabot
    image: zappabot:latest
    restart: always
    env_file:
      - .env
    build: ./
    ports:
      - "${PORT}:3000"
    volumes:
      - .:/usr/src/app
      - ./database/database.sqlite:/app/database/database.sqlite
